### Login request
POST {{url}}/api/login
Content-Type: application/json

{
  "email": "demo@dantofema.ar",
  "password": "demo"
}

> {%
    client.global.set("token", response.body.access_token)
%}

### Example of using the saved token
GET {{url}}/api/v1/home
Authorization: Bearer {{token}}

### Logout request
GET {{url}}/api/v1/home
Authorization: Bearer {{token}}
Content-Type: application/json
